### PR TITLE
EGA 320x200 and 640x200 16 colors

### PR DESCRIPTION
**Pull request by FrenkelS**

### CODE REVIEW

**Comment by FrenkelS** [comment]
Work-in-progress download link
https://github.com/FrenkelS/Doom8088/releases/tag/v20241206

and videos
https://www.youtube.com/watch?v=vdx2cNh9big
https://www.youtube.com/watch?v=DLcz4BFoAI0

**Comment by sneakernets** [comment]
WOOOOW I ran both on my 286 and they're as fast as the large text mode versions!

High single digits in frame rate sometimes but hey this is great stuff!

**Comment by sneakernets** [comment]
Is there another build I can test out soonish? Thanks for all the work you do 🤠

**Comment by FrenkelS** [comment]
Here you go:
[DOOM8088-EGA-v20241219.zip](https://github.com/user-attachments/files/18195736/DOOM8088-EGA-v20241219.zip)

**Comment by sneakernets** [comment]
Thank you! The 286 medium version works great - 286 high version is crashing on level load, not sure what's going on there. 256KB EGA card.

**Comment by FrenkelS** [comment]
no error message?

**Comment by sneakernets** [comment]
No, it's locking up the system and I have to force reboot. Demo3 begins(because I hear doomguy pick up an item) but it locks right after that, before the screen wipe.

**Comment by FrenkelS** [comment]
both 8088 and 286 versions?

**Comment by sneakernets** [comment]
I just tested the 8088  high version and it crashed on the same place.

**Comment by FrenkelS** [comment]
new version
[DOOM8088-EGA-v20241220.zip](https://github.com/user-attachments/files/18203976/DOOM8088-EGA-v20241220.zip)

**Comment by sneakernets** [comment]
Hey that worked! Thanks! What was the fix if I may ask? I'm curious

**Comment by FrenkelS** [comment]
I'm not sure. I think I overflowed the near memory when I recently moved the colormap to it. A strange thing happened to the Tandy 1000 builds: It would take a long time to load the WAD file into XMS memory.

Now I've freed up some near memory by making the drawsegs and vissprites arrays smaller by lowering MAXDRAWSEGS and MAXVISSPRITES. And now the Tandy builds are fast again. And apparently it also fixed the EGA builds.

**Pull request merged**
